### ISSUE TITLE
Icon looks stretched when mail label is a bit long

### ISSUE THREAD

**Issue by smknstd** [Xammie/mailbook#31]
![Screenshot from 2022-12-20 16-17-19](https://user-images.githubusercontent.com/2412608/208701684-b428b35c-207e-4c4b-9221-0902cc403653.png)

**Comment by Xammie** [comment]
Fixed in version 1.4.1

**Comment by smknstd** [comment]
Problem seems fixed with variants ! Unfortunately I still see shrinked icons on first level:

![Screenshot from 2023-01-05 11-29-25](https://user-images.githubusercontent.com/2412608/210759312-f389fc87-21f9-4eb0-8f41-0f8c3253eea9.png)

**Comment by Xammie** [comment]
It seems that I missed this one, fixed in 1.5.1
