### ISSUE TITLE
Support Laravel 8 again

### ISSUE THREAD

**Issue by MatthewLoffredo** [Xammie/mailbook#48]
In a previous commit, Laravel 8 support [#19](https://github.com/Xammie/mailbook/pull/19), the following got updated in composer.json:

`"illuminate/contracts": "^8.0|^9.0"`

In a later commit, it got changed back to:

`"illuminate/contracts": "^9.0"`

Which is not allowing me to install on my Laravel 8 environment. Please add this back to support Laravel 8 again.

**Comment by Xammie** [comment]
Previously it has been a hassle to keep supporting laravel 8. This is the reason I have removed it version 1.5.0. However you can still use the versions before that with laravel 8 support.

```
composer require xammie/mailbook "1.4.1"
```
