### ISSUE TITLE
Mailbook keeps sending emails when preview

### ISSUE THREAD

**Issue by Qoraiche** [Xammie/mailbook#67]
Hello. Thanks for this package,

I have an issue that I keep receiving emails every time I open a notification or mailable for preview.

I'm using:
```
"laravel/framework": "^10.10",
 "xammie/mailbook": "^1.7"
```

code:
```php
use App\Mail\MailbookMail;
use App\Models\User;
use Xammie\Mailbook\Facades\Mailbook;

//Mailbook::add(MailbookMail::class);

Mailbook::add(function (): MailbookMail {
    $user = User::factory()->make();

    return new MailbookMail($user);
});
```

Thanks

**Comment by Xammie** [comment]
Hello there, I am sadly unable to reproduce your issue. 

Could please provide me with more information or a reproduction example?
- Setup information (eg: PHP, other composer dependencies, OS)
- What does your `mailbook.php` config file look like?
- Where are the mails being sent to?
- Does this also happen for you in a clean laravel install?

```bash
composer create-project laravel/laravel mailbook-issue-67
cd mailbook-issue-67
composer require xammie/mailbook
php artisan mailbook:install
php artisan serve
```

**Comment by Qoraiche** [comment]
Setup information (eg: PHP, other composer dependencies, OS)
- php 8.1.10, fresh laravel ^10.10 dependencies, with latest Telescope package

What does your mailbook.php config file look like?
- I've only changed the send emails and database rollback settings.

Where are the mails being sent to?
- test@mailbook.dev

Does this also happen for you in a clean laravel install?
- yes

Note: I only receive mails on the locally installed telescope mail log, i didn't test it on production.

i don't know how mailbooks work but I think it somehow sends preview emails to a created driver (mail.mailbook) every time I access /mailbook route?

**Comment by Qoraiche** [comment]
> Hello there, I am sadly unable to reproduce your issue.
> 
> Could please provide me with more information or a reproduction example?
> 
> * Setup information (eg: PHP, other composer dependencies, OS)
> * What does your `mailbook.php` config file look like?
> * Where are the mails being sent to?
> * Does this also happen for you in a clean laravel install?
> 
> ```shell
> composer create-project laravel/laravel mailbook-issue-67
> cd mailbook-issue-67
> composer require xammie/mailbook
> php artisan mailbook:install
> php artisan serve
> ```

Setup information (eg: PHP, other composer dependencies, OS)

- php 8.1.10, fresh laravel ^10.10 dependencies, with latest Telescope package

What does your mailbook.php config file look like?

- I've only changed the send emails and database rollback settings.

Where are the mails being sent to?

- [test@mailbook.dev](mailto:test@mailbook.dev)

Does this also happen for you in a clean laravel install?

- yes

Note: I only receive mails on the locally installed telescope mail log, i didn't test it on production.

i don't know how mailbooks work but I think it somehow sends preview emails to a created driver (mail.mailbook) every time I access /mailbook route?

**Comment by Xammie** [comment]
Oh that is interesting. I have not used telescope before with Mailbook. Mailbook works by sending mailables or notification through an injected driver. What the driver does is make it possible to capture the result of this sent mail and display it in the browser. Even though the driver ensures does nothing more than store the SentMessage result, telescope probably assumes it has been sent because it went through the driver. 

You should not be worried at all that this would actually send a message, but I understand it might make the telescope mail entries a bit cluttered. I think you can solve it by doing some [filtering in the telescope entries](https://laravel.com/docs/10.x/telescope#filtering-entries). For example:

```php
Telescope::filter(function (IncomingEntry $entry) {
    if ($entry->type === 'mail' && Str::startsWith(request()->path(), 'mailbook')) {
        return false;
    }
    // ...
});
```

Hope this helps, and thanks for reporting your issue.
