### ISSUE TITLE
Undefined variable $mailables

### ISSUE THREAD

**Issue by alanmolnar** [Xammie/mailbook#76]
Hi, thanks for this great plugin, it really helps a lot.

I have issue when I moved everything to the server from my xampp, I'm getting error "Undefined variable $mailables" in [resources / views / vendor / mailbook / list.blade.php : 3].

PHP 8.2.16
Laravel 10.48.3

Mailbook routes file is same on my xampp and server, but on server there is no $mailables from some reason.

Can you please advice?

Thanks,
Alan

**Comment by Xammie** [comment]
Hello! Glad you like mailbook.

- What mailbook version doe you have installed?
- Can you verify that your view cache has been cleared? `php artisan view:clear`
- Does this issue also happen when you install mailbook in a empty project?

```
composer create-project laravel/laravel mailbook-issue-76
cd mailbook-issue-76
composer require xammie/mailbook
php artisan mailbook:install
php artisan serve
```

**Comment by Xammie** [comment]
Have you been able to reproduce this issue on a clean install? I'm closing this issue for now.
